### PR TITLE
Migrated to AndroidX and other small nits.

### PR DESCRIPTION
**Pull request by juliocbcotta**

### CODE REVIEW

**Comment by karnadii** [comment]
@BugsBunnyBR can you increment the version in pubscpec.yml as well?

**Comment by juliocbcotta** [comment]
Done.

**Comment by karnadii** [comment]
merged, thanks for your contribution

**Comment by karnadii** [comment]
sorry, this is my first time merging a pr, and I don't realize I merge it under my name.

**Comment by juliocbcotta** [comment]
No problem doc. :-)

**Pull request merged**
